log: false
dataset: "CiteSeer"
imbtype: "topology"
imb_ratio: 1
shuffle_seed: 47
random_seed: 1
backbone: "GCN"
metric: "acc"
nlayer: 2
epochs: 500
least_epoch: 30
early_stop: 10
nhid: 32
lr: 0.002
dropout: 0.5
adj: "norm"
weight_decay: 0.00075

least_Pre_epochs: 40
pre_epochs: 200
pre_lr: 0.005

threshold: 0.5
graph_skip_conn: 0.8
update_adj_ratio: 0.2
gsl_dropout: 0.5
iters: 1

mixnum: 0.4
lam: 0.5
select: "gain"
alpha: 0.1

pmt_lr: 0.05
pmt_weight_decay: 0.000001
pmt_dropout: 0

tau1: 0.15
tau2: 0.15
k: 10
n: 3
m: 5
num_triplets: 1000

gsl_dropout: 0.5
graph_skip_conn: 0.8
iters2: 10

topo_lr: 0.15
topo_weight_decay: 0.0001