log: false
dataset: "Cora"
imbtype: "classnum"
imb_ratio: 20
shuffle_seed: 29
random_seed: 1
backbone: "GCN"
metric: "loss"
epochs: 200
least_epoch: 100
early_stop: 10
nlayer: 2
nhid: 64
lr: 0.001
dropout: 0.5
adj: "norm"
weight_decay: 0.0004

least_Pre_epochs: 40
pre_epochs: 200
pre_lr: 0.005

threshold: 0.5
update_adj_ratio: 0.2
gsl_dropout: 0.2
iters: 1

mixnum: 0.5
lam: 0.7
alpha: 0.1

pmt_lr: 0.2
pmt_weight_decay: 0.000001
pmt_dropout: 0

tau1: 0.1
tau2: 0.1
k: 10
n: 3
m: 5
num_triplets: 1000

gsl_dropout: 0.5
graph_skip_conn: 0.8
iters2: 5

topo_lr: 0.2
topo_weight_decay: 0.001
